### PR TITLE
I can open REPL only by Ctrl+Shift+:

### PR DESCRIPTION
**Pull request by ankitest**

### CODE REVIEW

**Comment by dae** [comment]
On your keyboard, are ; and : on the same key? Which character do you get if you press the key with the shift key held down?

**Comment by ankitest** [comment]
On the same key.  : colon

**Comment by dae** [comment]
Yes, and you need to press shift to get : instead of ; right? The reason we don't write ctrl+shift+: is because the ; and : symbols are on different keys on some international keyboards.

**Comment by ankitest** [comment]
OK, then it may be better to write so?

> press Ctrl+: or Ctrl+Shift+; (or Command+: or Command+Shift+; it depends on you keyboard layout) and a window will open up.

Maybe it would be better to add a new command in Tools menu?

**Comment by dae** [comment]
It's already mentioned in the main manual - I have added a link back there instead.

**Comment by dae** [comment]
(thanks for the report :-)

**Pull request closed without merging**
